### ISSUE TITLE
default directory of training model

### ISSUE THREAD

**Issue by 1585596474** [OpenDriveLab/TCP#72]
Thank you for sharing your code.

I have trained the model, but I cannot find you. I have not modified any code. Can you tell me the default directory of saving the ckpt file?
![Screenshot from 2024-10-12 21-09-28](https://github.com/user-attachments/assets/ee9a9f0f-3bc7-4fc3-8796-6dae2035d788)

**Comment by 1585596474** [comment]
<img width="859" alt="image" src="https://github.com/user-attachments/assets/bddee2b2-aeed-44d6-8a2a-3594a8021cf4">
I found the default directory and modified the runevaluation.sh. and I met a problem. How can I solve this?

`The scenario could not be loaded:
> 'LeaderboardEvaluator' object has no attribute 'traffic_manager'

Traceback (most recent call last):
  File "/mnt/ssd/TCP/leaderboard/leaderboard/leaderboard_evaluator.py", line 350, in _load_and_run_scenario
    self._load_and_wait_for_world(args, config.town, config.ego_vehicles)
  File "/mnt/ssd/TCP/leaderboard/leaderboard/leaderboard_evaluator.py", line 232, in _load_and_wait_for_world
    self.traffic_manager.set_synchronous_mode(False)
AttributeError: 'LeaderboardEvaluator' object has no attribute 'traffic_manager'
> Registering the route statistics`
